#!/bin/sh

set -eu

mode="$(/usr/libexec/core/get-mode mode)" ||
    mode="$(/usr/libexec/core/get-arg snapd_recovery_mode)" || mode="unknown"

cat <<'EOF' >>/sysroot/etc/fstab
/run/mnt/data /writable none bind,x-initrd.mount 0 0
EOF

if [ "$mode" != "run" ]; then
    cat <<'EOF' >>/sysroot/etc/fstab
/run/mnt/kernel/firmware /usr/lib/firmware none bind,x-initrd.mount 0 0
/run/mnt/kernel/modules /usr/lib/modules none bind,x-initrd.mount 0 0
EOF
fi
